AWSTemplateFormatVersion: "2010-09-09"

Description: IAM Role for EC2 CloudWatchLogs

Resources:
  EC2RoleForCloudWatchLogs:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2RoleForCloudWatchLogs
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
  InstanceProfileforEC2:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: InstanceProfileForCloudWatchLogs
      Roles:
        - !Ref EC2RoleForCloudWatchLogs

Outputs:
  InstanceProfileId:
    Value: !Ref InstanceProfileforEC2
    Export:
      Name: InstanceProfileId
  InstanceProfileArn:
    Value: !GetAtt InstanceProfileforEC2.Arn
    Export:
      Name: InstanceProfileArn